### ISSUE TITLE
Moving Winapp2 respo to the other respo

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/winapp2.ini#1]
Now that BleachBit's version of Winapp2 is maintained by the official Winapp2 community, this respo is unneeded. I think we can move Winapp2 to @az0 respo and then I can update it from there and you can push the update through to BleachBit or even do a automatic process, too (and also I don't think anyone even knows this is even here).

**Comment by az0** [comment]
While I agree most no one knows this repository is here, the `merge-commit.sh` script still provides useful functions
1. More unnecessary default= lines to save space
2. Switch from DOS to UNIX encoding to save more space
3. Check for duplicate sections
4. Check for duplicate options within section

I would like to retain these functions.

Thoughts?

**Comment by ROCKNROLLKID** [comment]
@ShaneGowland uploaded a similar tool on the main Winapp2 respo, but it isn't as through as the merge script. You can check it out here: https://github.com/MoscaDotTo/Winapp2/tree/master/Tools/WinappDebug

Perhaps you can combine yours with his?

**Comment by az0** [comment]
I opened https://github.com/MoscaDotTo/Winapp2/issues/45 to address #3 and #4 (duplicates) above. Let's see how this goes, and then move on to #1 and #2 (compression)

**Comment by az0** [comment]
The processing here is still useful to find upstream errors and optimize the size, so I am going to close this issue.
