### ISSUE TITLE
Update Winapp2

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/winapp2.ini#12]
New Winapp2 update is ready for BleachBit. Changes mostly include Winapp2 now being licensed under CC-BY-SA 4.0, and some new additions and edits from the community.

**Comment by ROCKNROLLKID** [comment]
@azo I would like to get Winapp2 updated to the latest version so you can have a licensed copied to help protect Winapp2. Any chance you can pull the latest from upstream?

**Comment by az0** [comment]
I updated it
