### ISSUE TITLE
As far as I can tell the "MS Visual Studio 2017 Installation packages" cleaner causes issues

### ISSUE THREAD

**Issue by assarbad** [bleachbit/winapp2.ini#14]
This cleaner entry:

```
[MS Visual Studio 2017 Installation packages *]
LangSecRef=3021
Detect=HKCU\Software\Microsoft\VisualStudio
FileKey1=%CommonAppData%\Microsoft\VisualStudio\Packages|*.*|RECURSE
ExcludeKey1=PATH|%CommonAppData%\Microsoft\VisualStudio\Packages\_Instances\|*.*
```

seems to cause that the Visual Studio Installer does no longer recognize an already installed Visual Studio 2017. Consequently you won't be able to upgrade to a newer (sub)version of Visual Studio 2017 and so on.

At the very least at this point I think I have narrowed it down to that root cause.

Best regards,

Oliver

**Comment by az0** [comment]
Thank you for the bug report. Assuming BleachBit carries out the instructions as written, I believe this bug report belongs in the upstream repository https://github.com/MoscaDotTo/Winapp2/ .   

Sorry, this may be confusing. There is some more explanation about the distinction  here https://github.com/bleachbit/winapp2.ini/blob/master/README.md .

**Comment by assarbad** [comment]
Hi @az0 , thanks. No problem. Perhaps you could add a template for new issues which mentions this. I didn't realize this until your comment.

Best regards,

Oliver
