### ISSUE TITLE
[Feature Request] Microsoft Teams cleanup

### ISSUE THREAD

**Issue by ltdeta** [bleachbit/winapp2.ini#18]
I have found only the configuration for CCCleaner
https://albandrodsmemory.wordpress.com/2019/01/04/microsoft-teams-how-to-clean-cache/

For all CCleaner users, you may add following lines to C:\Program Files\CCleaner\winapp2.ini:

[Microsoft Teams *]
LangSecRef=3021
Default=True
DetectFile=%LocalAppData%\Microsoft\Teams
FileKey1=%AppData%\Microsoft\Teams\application cache\cache|*|RECURSE
FileKey2=%AppData%\Microsoft\Teams\blob_storage|*|RECURSE
FileKey3=%AppData%\Microsoft\Teams\Cache|*|RECURSE
FileKey4=%AppData%\Microsoft\Teams\databases|*|RECURSE
FileKey5=%AppData%\Microsoft\Teams\GPUcache|*|RECURSE
FileKey6=%AppData%\Microsoft\Teams\IndexedDB|*|RECURSE
FileKey7=%AppData%\Microsoft\Teams\Local Storage|*|RECURSE
FileKey8=%AppData%\Microsoft\Teams\tmp|*|RECURSE
FileKey9=%AppData%\Microsoft\Teams\Service Worker\CacheStorage|*|REMOVESELF
FileKey10=%AppData%\Microsoft\Teams|old_logs_*.txt
;remove previous version:
FileKey11=%LocalAppData%\Microsoft\Teams\previous\|*.*|REMOVESELF

**Comment by az0** [comment]
Please submit changes for Winapp2.ini to the Winapp2.ini page as explained here https://github.com/bleachbit/winapp2.ini/blob/master/README.md
