### ISSUE TITLE
Winapp2.ini updated, but Winapp2-BleachBit.ini not updated

### ISSUE THREAD

**Issue by Gitoffthelawn** [bleachbit/winapp2.ini#19]
I noticed Winapp2.ini was updated, but Winapp2-BleachBit.ini was not updated.

Was this intentional, just a reflection of the automated process not running yet, or perhaps an oversight?

**Comment by az0** [comment]
Good catch. Thank you

**Comment by Gitoffthelawn** [comment]
You're welcome. :)

**Comment by az0** [comment]
I took a closer look. Short explanation: The [upstream version ](https://github.com/MoscaDotTo/Winapp2/tree/master/Non-CCleaner) has not been updated in three months, which shows in the Git history. The header of the file has the version 210913.

**Comment by Gitoffthelawn** [comment]
@az0 It looks like you made an edit to the copy of the upstream file (`Winapp2.ini`) located in this repo about a week ago (https://github.com/bleachbit/winapp2.ini/commit/f7916d309eba8025b866a08ac5e6b75c38ab2f6e).  How do your changes get implemented into `Winapp2-Bleachbit.ini` if the trigger is the upstream version getting modified?

**Comment by Gitoffthelawn** [comment]
@az0 Ping :)
