### ISSUE TITLE
Can't update the file

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/winapp2.ini#2]
GitHub doesn't seem to want to let me update the file anymore. Every time I try to, it either splits the file or it doesn't copy the whole thing.

@az0  Any chance you can update the file with the one here: https://github.com/MoscaDotTo/Winapp2/tree/master/Non-CCleaner

**Comment by az0** [comment]
There are many duplicate keys. I will file a bug there. Please reopen here when it is resolved. Thanks.

**Comment by ROCKNROLLKID** [comment]
Should be fixed.

**Comment by az0** [comment]
I pushed the new file
