### ISSUE TITLE
Outdated Winapp.ini

### ISSUE THREAD

**Issue by GoldMath** [bleachbit/winapp2.ini#3]
Hi,

The Winapp.ini database I got with BleachBit (1.12) by ticking the option is **161214**; 
[While the community one](https://github.com/MoscaDotTo/Winapp2) is, period, **170724**. Here the header of the old one.

Also a display of the Winapp.ini version in BleachBit could be a plus.

Regards,
```
; Winapp2.ini for BleachBit
;  2625 entries
;  https://github.com/az0/winapp2.ini/

; Version: v5.25.161214
; Application Cleaning file
;
; Notes
; # of entries: 2,578 + 52 removed entries
; This file is the non-CCleaner version of Winapp2. This file is intended for BleachBit, System Ninja and Avira System Speedup users.
; This file contains all the removed entries that were lost due to CCleaner. The removed entries are located at the bottom of the file.
; Please do not host this file anywhere without permission. This is to facilitate proper distribution of the latest version. Thanks.
```

**Comment by ROCKNROLLKID** [comment]
Yes, we have been meaning to get it updated. For now, you can disable the auto update and manually update the file from upstream.

**Comment by ROCKNROLLKID** [comment]
I updated it. Waiting for Andrew to push it through the updater.

**Comment by az0** [comment]
The other day I pushed out a new Winapp2.ini. Thank you for the reminder.
