### ISSUE TITLE
Updated Winapp2

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/winapp2.ini#4]
@az0 I updated Winapp2 to latest Upstream. You can push it through BleachBit at anytime.

Also, I will try to get back into updating this once a month.

**Comment by ROCKNROLLKID** [comment]
@azo Just updated the file here with the fixes you provided at the main respo as well as a few new/modified entries from upstream. Should be good to go.

**Comment by az0** [comment]
Thanks.

Fixed in Git commit 74d96506ca00204faf1e7b656826d23e77a8209a
