### ISSUE TITLE
Suggestions for Winapp2 analyzers

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/winapp2.ini#5]
Recently we come across some more issues that I think could belong to your analyzers.

* Make sure environment variables are surrounded by %. So all entries should be like this: FileKey#= %variable%

* Make sure variables are spelled correctly. It has never been a issue, but there are only 13 variables that can be used and anything else won't work. Ignore if RegKey is present within the line. The list is below:

%AppData%

%CommonAppData%

%CommonProgramFiles%

%HomeDrive%

%LocalAppData%

%ProgramFiles%

%SystemDrive%

%UserProfile%

%WinDir%

%Pictures%

%Documents%

%Video%

%Music%

**Comment by az0** [comment]
I added to the merge script to find `variable%` or `%variable` without the matching `%`

In the existing `profile.sh` script is a part to count environment variables, and it currently has
````
Environment variables
      2 %AllUsersProfile%
   1370 %AppData%
    680 %CommonAppData%
     25 %CommonProgramFiles%
    357 %Documents%
      5 %HomeDrive%
   3273 %LocalAppData%
     41 %LocalLowAppData%
      5 %Music%
     16 %Pictures%
   1173 %ProgramFiles%
     16 %Public%
      1 %RootDir%
    211 %SystemDrive%
      1 %SystemRoot%
      3 %Temp%
      1 %user%
    160 %UserProfile%
      2 %Video%
    258 %windir%
````
This looks a bit different than your list

**Comment by ROCKNROLLKID** [comment]
That is fine, but how come it didn't detect this issue: https://forum.piriform.com/index.php?showtopic=32310&p=287696

**Comment by ROCKNROLLKID** [comment]
Yes, that list is more correct, I just copied and pasted the list over at the first page on Winapp2, which I guess hasn't ever been updated. Anyways, thanks for the addition.
