### ISSUE TITLE
Updated from upstream

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/winapp2.ini#8]
@az0 Another update from upstream. This update included a minor overhaul from a few community members to remove unnecessary trailing backslashes, unnecessary detects for Wow6432node that was brought up here: https://github.com/bleachbit/bleachbit/issues/247 and several updates and modifications from the community.

**Comment by az0** [comment]
Thanks for the update. However, please do not delete a file to update it because it obscures the change history. I fixed it by un-commiting the delete.

**Comment by ROCKNROLLKID** [comment]
Alright.
