### ISSUE TITLE
New Winappdebug tool

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/winapp2.ini#9]
@az0 Robert got around to updating Winapp2debug and it is much more thorough then it was before. Would you mind testing it and seeing if there is anything missing that your tool does and winappdebug doesn't? I think he is willing to do more tweaks to it if needed.

You can find it here: https://github.com/MoscaDotTo/Winapp2/tree/master/Tools/WinappDebug

**Comment by az0** [comment]
OK

https://github.com/MoscaDotTo/Winapp2/issues/139

https://github.com/MoscaDotTo/Winapp2/issues/140

https://github.com/MoscaDotTo/Winapp2/issues/141
